module.exports = {
  totalItems: 10,
  resorts: [
    {
      id: 1,
      name: 'Grebenzen – St. Lambrecht',
      country: 'Austria',
      region: 'Styria (Steiermark)',
      totalSlopes: 12.2,
      blueSlopes: 2.9,
      redSlopes: 9,
      blackSlopes: 0.3,
      price: 38,
      breadcrumbs1:
        '[{"text":"Europe","href":"https://www.skiresort.info/ski-resorts/europe/"},{"text":"Austria","href":"https://www.skiresort.info/ski-resorts/austria/"},{"text":"Styria (Steiermark)","href":"https://www.skiresort.info/ski-resorts/styria-steiermark/"},{"text":"Murtal","href":"https://www.skiresort.info/ski-resorts/murtal/"}]',
      breadcrumbs2:
        '[{"text":"Europe","href":"https://www.skiresort.info/ski-resorts/europe/"},{"text":"Austria","href":"https://www.skiresort.info/ski-resorts/austria/"},{"text":"Styria (Steiermark)","href":"https://www.skiresort.info/ski-resorts/styria-steiermark/"},{"text":"Murtal","href":"https://www.skiresort.info/ski-resorts/murtal/"}]',
      breadcrumbs3: null,
      mainLink: 'https://www.skiresort.info/ski-resort/grebenzen-st-lambrecht/',
      placeId: null,
      latitude: '47.0333333',
      longitude: '14.3333333',
      createdAt: '2021-03-18T08:19:41.000Z',
      updatedAt: '2021-03-25T18:31:01.000Z',
    },
    {
      id: 2,
      name: 'Mönichkirchen/Mariensee',
      country: 'Austria',
      region: 'Lower Austria (Niederösterreich)',
      totalSlopes: 13.5,
      blueSlopes: 5.5,
      redSlopes: 6,
      blackSlopes: 2,
      price: 38.5,
      breadcrumbs1:
        '[{"text":"Europe","href":"https://www.skiresort.info/ski-resorts/europe/"},{"text":"Austria","href":"https://www.skiresort.info/ski-resorts/austria/"},{"text":"Lower Austria (Niederösterreich)","href":"https://www.skiresort.info/ski-resorts/lower-austria-niederoesterreich/"},{"text":"Wiener Alpen","href":"https://www.skiresort.info/ski-resorts/wiener-alpen/"},{"text":"Neunkirchen","href":"https://www.skiresort.info/ski-resorts/neunkirchen/"}]',
      breadcrumbs2:
        '[{"text":"Europe","href":"https://www.skiresort.info/ski-resorts/europe/"},{"text":"Austria","href":"https://www.skiresort.info/ski-resorts/austria/"},{"text":"Lower Austria (Niederösterreich)","href":"https://www.skiresort.info/ski-resorts/lower-austria-niederoesterreich/"},{"text":"Wiener Alpen","href":"https://www.skiresort.info/ski-resorts/wiener-alpen/"},{"text":"Neunkirchen","href":"https://www.skiresort.info/ski-resorts/neunkirchen/"}]',
      breadcrumbs3: null,
      mainLink:
        'https://www.skiresort.info/ski-resort/moenichkirchenmariensee/',
      placeId: null,
      latitude: '47.5122986000000',
      longitude: '16.0298176',
      createdAt: '2021-03-18T08:19:41.000Z',
      updatedAt: '2021-03-25T18:30:58.000Z',
    },
    {
      id: 3,
      name: 'Ramsau am Dachstein – Rittisberg',
      country: 'Austria',
      region: 'Styria (Steiermark)',
      totalSlopes: 25,
      blueSlopes: 14,
      redSlopes: 10,
      blackSlopes: 1,
      price: 39.5,
      breadcrumbs1:
        '[{"text":"Europe","href":"https://www.skiresort.info/ski-resorts/europe/"},{"text":"Austria","href":"https://www.skiresort.info/ski-resorts/austria/"},{"text":"Styria (Steiermark)","href":"https://www.skiresort.info/ski-resorts/styria-steiermark/"},{"text":"Liezen","href":"https://www.skiresort.info/ski-resorts/liezen/"},{"text":"Schladming-Dachstein","href":"https://www.skiresort.info/ski-resorts/schladming-dachstein/"}]',
      breadcrumbs2:
        '[{"text":"Europe","href":"https://www.skiresort.info/ski-resorts/europe/"},{"text":"Austria","href":"https://www.skiresort.info/ski-resorts/austria/"},{"text":"Styria (Steiermark)","href":"https://www.skiresort.info/ski-resorts/styria-steiermark/"},{"text":"Liezen","href":"https://www.skiresort.info/ski-resorts/liezen/"},{"text":"Schladming-Dachstein","href":"https://www.skiresort.info/ski-resorts/schladming-dachstein/"}]',
      breadcrumbs3: null,
      mainLink:
        'https://www.skiresort.info/ski-resort/ramsau-am-dachstein-rittisberg/',
      placeId: null,
      latitude: '47.4224958',
      longitude: '13.6235779',
      createdAt: '2021-03-18T08:19:41.000Z',
      updatedAt: '2021-03-25T18:28:46.000Z',
    },
    {
      id: 4,
      name: 'Schlick 2000 – Fulpmes',
      country: 'Austria',
      region: 'Tyrol (Tirol)',
      totalSlopes: 22,
      blueSlopes: 12,
      redSlopes: 6.8,
      blackSlopes: 3.2,
      price: 42,
      breadcrumbs1:
        '[{"text":"Europe","href":"https://www.skiresort.info/ski-resorts/europe/"},{"text":"Austria","href":"https://www.skiresort.info/ski-resorts/austria/"},{"text":"Tyrol (Tirol)","href":"https://www.skiresort.info/ski-resorts/tyrol-tirol/"},{"text":"Innsbruck","href":"https://www.skiresort.info/ski-resorts/innsbruck/"},{"text":"Innsbruck-Land","href":"https://www.skiresort.info/ski-resorts/innsbruck-land/"},{"text":"Stubai","href":"https://www.skiresort.info/ski-resorts/stubai/"}]',
      breadcrumbs2:
        '[{"text":"Europe","href":"https://www.skiresort.info/ski-resorts/europe/"},{"text":"Austria","href":"https://www.skiresort.info/ski-resorts/austria/"},{"text":"Tyrol (Tirol)","href":"https://www.skiresort.info/ski-resorts/tyrol-tirol/"},{"text":"Innsbruck","href":"https://www.skiresort.info/ski-resorts/innsbruck/"},{"text":"Innsbruck-Land","href":"https://www.skiresort.info/ski-resorts/innsbruck-land/"},{"text":"Stubai","href":"https://www.skiresort.info/ski-resorts/stubai/"}]',
      breadcrumbs3: null,
      mainLink: 'https://www.skiresort.info/ski-resort/schlick-2000-fulpmes/',
      placeId: null,
      latitude: '47.15561',
      longitude: '11.34363',
      createdAt: '2021-03-18T08:19:41.000Z',
      updatedAt: '2021-03-25T18:28:57.000Z',
    },
    {
      id: 5,
      name: 'Axamer Lizum',
      country: 'Austria',
      region: 'Tyrol (Tirol)',
      totalSlopes: 30,
      blueSlopes: 7,
      redSlopes: 21,
      blackSlopes: 2,
      price: 43,
      breadcrumbs1:
        '[{"text":"Europe","href":"https://www.skiresort.info/ski-resorts/europe/"},{"text":"Austria","href":"https://www.skiresort.info/ski-resorts/austria/"},{"text":"Tyrol (Tirol)","href":"https://www.skiresort.info/ski-resorts/tyrol-tirol/"},{"text":"Innsbruck region","href":"https://www.skiresort.info/ski-resorts/innsbruck-region/"}]',
      breadcrumbs2:
        '[{"text":"Europe","href":"https://www.skiresort.info/ski-resorts/europe/"},{"text":"Austria","href":"https://www.skiresort.info/ski-resorts/austria/"},{"text":"Tyrol (Tirol)","href":"https://www.skiresort.info/ski-resorts/tyrol-tirol/"},{"text":"Innsbruck region","href":"https://www.skiresort.info/ski-resorts/innsbruck-region/"}]',
      breadcrumbs3: null,
      mainLink: 'https://www.skiresort.info/ski-resort/axamer-lizum/',
      placeId: null,
      latitude: '47.19569',
      longitude: '11.30265',
      createdAt: '2021-03-18T08:19:41.000Z',
      updatedAt: '2021-03-25T18:29:26.000Z',
    },
    {
      id: 6,
      name: 'Tauplitz – Bad Mitterndorf',
      country: 'Austria',
      region: 'Styria (Steiermark)',
      totalSlopes: 43.5,
      blueSlopes: 18.5,
      redSlopes: 19,
      blackSlopes: 6,
      price: 44,
      breadcrumbs1:
        '[{"text":"Europe","href":"https://www.skiresort.info/ski-resorts/europe/"},{"text":"Austria","href":"https://www.skiresort.info/ski-resorts/austria/"},{"text":"Styria (Steiermark)","href":"https://www.skiresort.info/ski-resorts/styria-steiermark/"},{"text":"Salzkammergut","href":"https://www.skiresort.info/ski-resorts/salzkammergut/"},{"text":"Ausseerland","href":"https://www.skiresort.info/ski-resorts/ausseerland/"}]',
      breadcrumbs2:
        '[{"text":"Europe","href":"https://www.skiresort.info/ski-resorts/europe/"},{"text":"Austria","href":"https://www.skiresort.info/ski-resorts/austria/"},{"text":"Styria (Steiermark)","href":"https://www.skiresort.info/ski-resorts/styria-steiermark/"},{"text":"Salzkammergut","href":"https://www.skiresort.info/ski-resorts/salzkammergut/"},{"text":"Ausseerland","href":"https://www.skiresort.info/ski-resorts/ausseerland/"}]',
      breadcrumbs3: null,
      mainLink:
        'https://www.skiresort.info/ski-resort/tauplitz-bad-mitterndorf/',
      placeId: null,
      latitude: '47.5611156999999',
      longitude: '14.0118664',
      createdAt: '2021-03-18T08:19:41.000Z',
      updatedAt: '2021-03-25T18:28:36.000Z',
    },
    {
      id: 7,
      name: 'Lachtal',
      country: 'Austria',
      region: 'Styria (Steiermark)',
      totalSlopes: 26.2,
      blueSlopes: 7.2,
      redSlopes: 16,
      blackSlopes: 3,
      price: 45,
      breadcrumbs1:
        '[{"text":"Europe","href":"https://www.skiresort.info/ski-resorts/europe/"},{"text":"Austria","href":"https://www.skiresort.info/ski-resorts/austria/"},{"text":"Styria (Steiermark)","href":"https://www.skiresort.info/ski-resorts/styria-steiermark/"},{"text":"Murtal","href":"https://www.skiresort.info/ski-resorts/murtal/"}]',
      breadcrumbs2:
        '[{"text":"Europe","href":"https://www.skiresort.info/ski-resorts/europe/"},{"text":"Austria","href":"https://www.skiresort.info/ski-resorts/austria/"},{"text":"Styria (Steiermark)","href":"https://www.skiresort.info/ski-resorts/styria-steiermark/"},{"text":"Murtal","href":"https://www.skiresort.info/ski-resorts/murtal/"}]',
      breadcrumbs3: null,
      mainLink: 'https://www.skiresort.info/ski-resort/lachtal/',
      placeId: null,
      latitude: '47.1894654',
      longitude: '14.346014',
      createdAt: '2021-03-18T08:19:41.000Z',
      updatedAt: '2021-03-25T18:29:25.000Z',
    },
    {
      id: 8,
      name: 'Sonnenkopf – Klösterle',
      country: 'Austria',
      region: 'Vorarlberg',
      totalSlopes: 29.5,
      blueSlopes: 12.8,
      redSlopes: 15.9,
      blackSlopes: 0.8,
      price: 45,
      breadcrumbs1:
        '[{"text":"Europe","href":"https://www.skiresort.info/ski-resorts/europe/"},{"text":"Austria","href":"https://www.skiresort.info/ski-resorts/austria/"},{"text":"Vorarlberg","href":"https://www.skiresort.info/ski-resorts/vorarlberg/"},{"text":"Bludenz","href":"https://www.skiresort.info/ski-resorts/bludenz/"},{"text":"Alpenregion Bludenz","href":"https://www.skiresort.info/ski-resorts/alpenregion-bludenz/"}]',
      breadcrumbs2:
        '[{"text":"Europe","href":"https://www.skiresort.info/ski-resorts/europe/"},{"text":"Austria","href":"https://www.skiresort.info/ski-resorts/austria/"},{"text":"Vorarlberg","href":"https://www.skiresort.info/ski-resorts/vorarlberg/"},{"text":"Bludenz","href":"https://www.skiresort.info/ski-resorts/bludenz/"},{"text":"Alpenregion Bludenz","href":"https://www.skiresort.info/ski-resorts/alpenregion-bludenz/"}]',
      breadcrumbs3: null,
      mainLink: 'https://www.skiresort.info/ski-resort/sonnenkopf-kloesterle/',
      placeId: null,
      latitude: '47.1286493',
      longitude: '10.0559643',
      createdAt: '2021-03-18T08:19:41.000Z',
      updatedAt: '2021-03-25T18:28:55.000Z',
    },
    {
      id: 9,
      name: 'Almenwelt Lofer',
      country: 'Austria',
      region: 'Salzburg (Salzburger Land)',
      totalSlopes: 46,
      blueSlopes: 32,
      redSlopes: 12,
      blackSlopes: 2,
      price: 46,
      breadcrumbs1:
        '[{"text":"Europe","href":"https://www.skiresort.info/ski-resorts/europe/"},{"text":"Austria","href":"https://www.skiresort.info/ski-resorts/austria/"},{"text":"Salzburg (Salzburger Land)","href":"https://www.skiresort.info/ski-resorts/salzburg-salzburger-land/"},{"text":"Pinzgau","href":"https://www.skiresort.info/ski-resorts/pinzgau/"},{"text":"Salzburger Saalachtal","href":"https://www.skiresort.info/ski-resorts/salzburger-saalachtal/"}]',
      breadcrumbs2:
        '[{"text":"Europe","href":"https://www.skiresort.info/ski-resorts/europe/"},{"text":"Austria","href":"https://www.skiresort.info/ski-resorts/austria/"},{"text":"Salzburg (Salzburger Land)","href":"https://www.skiresort.info/ski-resorts/salzburg-salzburger-land/"},{"text":"Pinzgau","href":"https://www.skiresort.info/ski-resorts/pinzgau/"},{"text":"Salzburger Saalachtal","href":"https://www.skiresort.info/ski-resorts/salzburger-saalachtal/"}]',
      breadcrumbs3: null,
      mainLink: 'https://www.skiresort.info/ski-resort/almenwelt-lofer/',
      placeId: null,
      latitude: '47.5878255',
      longitude: '12.69144',
      createdAt: '2021-03-18T08:19:41.000Z',
      updatedAt: '2021-03-25T18:27:47.000Z',
    },
    {
      id: 10,
      name: 'St. Johann in Tirol/Oberndorf – Harschbichl',
      country: 'Austria',
      region: 'Tyrol (Tirol)',
      totalSlopes: 42,
      blueSlopes: 15.5,
      redSlopes: 23,
      blackSlopes: 3.5,
      price: 48,
      breadcrumbs1:
        '[{"text":"Europe","href":"https://www.skiresort.info/ski-resorts/europe/"},{"text":"Austria","href":"https://www.skiresort.info/ski-resorts/austria/"},{"text":"Tyrol (Tirol)","href":"https://www.skiresort.info/ski-resorts/tyrol-tirol/"},{"text":"Tiroler Unterland","href":"https://www.skiresort.info/ski-resorts/tiroler-unterland/"},{"text":"Kitzbüheler Alpen","href":"https://www.skiresort.info/ski-resorts/kitzbueheler-alpen/"},{"text":"St. Johann in Tirol","href":"https://www.skiresort.info/ski-resorts/st-johann-in-tirol/"}]',
      breadcrumbs2:
        '[{"text":"Europe","href":"https://www.skiresort.info/ski-resorts/europe/"},{"text":"Austria","href":"https://www.skiresort.info/ski-resorts/austria/"},{"text":"Tyrol (Tirol)","href":"https://www.skiresort.info/ski-resorts/tyrol-tirol/"},{"text":"Tiroler Unterland","href":"https://www.skiresort.info/ski-resorts/tiroler-unterland/"},{"text":"Kitzbüheler Alpen","href":"https://www.skiresort.info/ski-resorts/kitzbueheler-alpen/"},{"text":"St. Johann in Tirol","href":"https://www.skiresort.info/ski-resorts/st-johann-in-tirol/"}]',
      breadcrumbs3: null,
      mainLink:
        'https://www.skiresort.info/ski-resort/st-johann-in-tiroloberndorf-harschbichl/',
      placeId: null,
      latitude: '47.5169098999999',
      longitude: '12.4268232',
      createdAt: '2021-03-18T08:19:41.000Z',
      updatedAt: '2021-03-25T18:28:41.000Z',
    },
  ],
  totalPages: 1,
  currentPage: 1,
};
